logging:
  file: ${HOME}/logs/${spring.application.name}.log
  level:
    root: info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:11000/eureka/

spring:
  profiles:
    active: local

  http:
    encoding:
      force: true

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss
    serialization:
      indentOutput: true


