server:
  port: 11002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:11000/eureka/

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/crs?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123