server:
  port: 11000

logging:
  file: ${HOME}/logs/${spring.application.name}.log
  level:
    root: info

eureka:
  instance:
    hostname: 0.0.0.0
  server:
    enable-self-preservation: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: crs-eureka-server

  http:
    encoding:
      force: true

  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss
    serialization:
      indentOutput: true