spring:
  application:
      name: EurekaServer

logging:
  file: ${HOME}/logs/${spring.application.name}.log
  level:
    root: info

server:
  port: 11000

eureka:
  instance:
    hostname: 0.0.0.0
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/