spring:
  application:
      name: CrsAuthServer

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/crs_auth?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  jackson:
    serialization:
      indent_output: true

server:
  port: 11001

logging:
  file: ${HOME}/logs/${spring.application.name}.log
  level:
    root: info
