server:
  port: 11003

eureka:
  client:
    serviceUrl:
      defaultZone: http://101.132.159.21:11000/eureka/

spring:
  datasource:
    url: jdbc:mysql://101.132.159.21:3306/crs_forum?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
