server:
  port: 11002

logging:
  file: ${HOME}/logs/${spring.application.name}.log
  level:
    root: info

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:11000/eureka/

spring:
  application:
    name: crs-auth-client

  http:
    encoding:
      force: true

  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss
    serialization:
      indentOutput: true
